#基础镜像，如果本地仓库没有，会从远程仓库拉取
#FROM openjdk:11
#暴露端口
#EXPOSE 8885
#容器中创建目录
#RUN mkdir -p /usr/local/cenobitor
#编译后的jar包copy到容器中创建到目录内
#COPY target/springboot-k8s.jar /pt-dev/test/app.jar
#指定容器启动时要执行的命令
#ENTRYPOINT ["java","-jar","/pt-dev/test/app.jar"]
FROM k8s.gcr.io/coredns:1.6.2